name: Build wheels
on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-13, macos-14]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build wheels
        env:
          CIBW_BUILD: cp310-* cp311-* cp312-* cp313-*
          CIBW_SKIP: pp*
        run: |
          cd src/pyquadkey2/quadkey/tilesystem
          python setup.py build_ext --inplace
          cd ../../../..
          pipx run cibuildwheel==2.22.0

      - uses: actions/upload-artifact@v4
        with:
          name: wheels-${{ matrix.os }}
          path: ./wheelhouse/*.whl

  create_release:
    needs: build_wheels
    runs-on: ubuntu-latest

    steps:
      - uses: actions/download-artifacts@4
        with:
          merge-multiple: true

      - uses: softprops/action-gh-release@v2
        with:
          name: "Release 0.3.1"
          tag_name: "0.3.1"
          draft: false
          prerelease: false
